# Generated by Django 5.2.5 on 2025-08-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('script_type', models.PositiveSmallIntegerField(choices=[(1, 'FFmpeg'), (2, 'OpenCV')], default=1)),
                ('fps', models.PositiveIntegerField(default=1)),
                ('detection_set', models.CharField(choices=[('auto', 'auto'), ('640', '640'), ('800', '800'), ('1024', '1024'), ('1600', '1600'), ('2048', '2048')], default='auto', max_length=16)),
                ('extra_args', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('cameras', models.ManyToManyField(blank=True, related_name='policies', to='cameras.camera')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='scheduler.schedulepolicy')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.streamprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['policy', 'day_of_week'], name='scheduler_s_policy__ca1f33_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('off', 'off'), ('on', 'on'), ('window', 'window')], max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='scheduler.schedulepolicy')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.streamprofile')),
            ],
            options={
                'unique_together': {('policy', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RunningProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='running', max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.streamprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['camera', 'profile'], name='scheduler_r_camera__344647_idx')],
            },
        ),
    ]
