# Generated by Django 5.2.5 on 2025-08-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True)),
                ('fps', models.FloatField(default=0)),
                ('detected', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=200)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.streamprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['camera', 'profile', 'ts'], name='scheduler_r_camera__f2c9bf_idx')],
            },
        ),
    ]
