# Generated by Django 5.2.5 on 2025-08-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('scheduler', '0002_runnerheartbeat'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='runningprocess',
            constraint=models.UniqueConstraint(fields=('camera', 'profile', 'pid'), name='uniq_cam_prof_pid'),
        ),
    ]
