# Generated by Django 5.2.5 on 2025-08-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_runningprocess_uniq_cam_prof_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningprocess',
            name='effective_opts',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='runnerheartbeat',
            name='last_error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
