# Generated by Django 5.2.5 on 2025-08-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_runningprocess_effective_opts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningprocess',
            name='effective_args',
            field=models.TextField(blank=True, null=True),
        ),
    ]
