# Generated by Django 5.2.5 on 2025-08-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_runningprocess_effective_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningprocess',
            name='cpu_affinity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runningprocess',
            name='effective_env',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='runningprocess',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='runningprocess',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runningprocess',
            name='nice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='effective_args',
            field=models.TextField(blank=True, default=''),
        ),
    ]
