# Generated by Django 5.2.5 on 2025-08-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_runningprocess_cpu_affinity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamprofile',
            name='cpu_affinity',
            field=models.CharField(blank=True, default='', help_text='e.g. "0,1"', max_length=64),
        ),
        migrations.AddField(
            model_name='streamprofile',
            name='device',
            field=models.CharField(blank=True, choices=[('', '(inherit)'), ('cpu', 'CPU'), ('cuda', 'CUDA')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='streamprofile',
            name='gpu_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamprofile',
            name='hb_interval',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Seconds between heartbeats', null=True),
        ),
        migrations.AddField(
            model_name='streamprofile',
            name='hwaccel',
            field=models.CharField(blank=True, choices=[('', '(inherit)'), ('none', 'none'), ('nvdec', 'nvdec')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='streamprofile',
            name='nice',
            field=models.SmallIntegerField(blank=True, help_text='Process niceness (-20..19)', null=True),
        ),
        migrations.AddField(
            model_name='streamprofile',
            name='rtsp_transport',
            field=models.CharField(blank=True, choices=[('', '(inherit)'), ('auto', 'auto'), ('tcp', 'tcp'), ('udp', 'udp')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='streamprofile',
            name='snapshot_every',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Snapshot every N heartbeats', null=True),
        ),
    ]
