# Generated by Django 5.2.5 on 2025-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_streamprofile_cpu_affinity_streamprofile_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningprocess',
            name='cpu_affinity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
