# Generated by Django 5.2.5 on 2025-08-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_runningprocess_cpu_affinity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runnerheartbeat',
            options={'ordering': ('-ts',)},
        ),
        migrations.RenameIndex(
            model_name='runnerheartbeat',
            new_name='hb_cam_prof_ts',
            old_name='scheduler_r_camera__f2c9bf_idx',
        ),
    ]
