# Generated by Django 5.2.5 on 2025-08-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_runnerheartbeat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerheartbeat',
            name='ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
