# Generated by Django 5.2.5 on 2025-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_runnerheartbeat_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerheartbeat',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
