# Generated by Django 5.2.5 on 2025-08-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_globalresourcesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerheartbeat',
            name='processed_fps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
