# Generated by Django 5.2.5 on 2025-09-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_runnerheartbeat_processed_fps'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningprocess',
            name='camera_fps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runningprocess',
            name='processed_fps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runningprocess',
            name='snapshot_every',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runningprocess',
            name='target_fps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
