# Generated by Django 5.2.5 on 2025-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_runningprocess_camera_fps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraresourceoverride',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Master toggle for considering any per-camera resource overrides.'),
        ),
        migrations.AddField(
            model_name='globalresourcesettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If disabled, global defaults/caps are ignored.'),
        ),
    ]
