# Generated by Django 5.2.5 on 2025-09-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_cameraresourceoverride_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraresourceoverride',
            name='device',
            field=models.CharField(blank=True, choices=[('', '(inherit)'), ('cpu', 'CPU'), ('cuda', 'CUDA')], help_text='Override compute device for this camera only.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='cameraresourceoverride',
            name='hwaccel',
            field=models.CharField(blank=True, choices=[('', '(inherit)'), ('none', 'none'), ('nvdec', 'nvdec')], help_text='Override decode accel for this camera only.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='globalresourcesettings',
            name='device',
            field=models.CharField(blank=True, choices=[('', '(inherit)'), ('cpu', 'CPU'), ('cuda', 'CUDA')], help_text='Default compute device (cuda/cpu). Null=not set here.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='globalresourcesettings',
            name='hwaccel',
            field=models.CharField(blank=True, choices=[('', '(inherit)'), ('none', 'none'), ('nvdec', 'nvdec')], help_text='Default decode accel (nvdec/none). Null=not set here.', max_length=8, null=True),
        ),
    ]
