# Generated by Django 5.2.5 on 2025-09-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_cameraresourceoverride_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamprofile',
            name='cpu_affinity',
        ),
        migrations.RemoveField(
            model_name='streamprofile',
            name='device',
        ),
        migrations.RemoveField(
            model_name='streamprofile',
            name='gpu_index',
        ),
        migrations.RemoveField(
            model_name='streamprofile',
            name='hwaccel',
        ),
        migrations.RemoveField(
            model_name='streamprofile',
            name='nice',
        ),
    ]
