# Generated by Django 5.2.5 on 2025-09-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_remove_streamprofile_cpu_affinity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerheartbeat',
            name='min_face_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
