# Generated by Django 5.2.5 on 2025-09-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_cameraresourceoverride_crop_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalresourcesettings',
            name='save_debug_unmatched',
            field=models.BooleanField(blank=True, help_text='If True, save below-threshold (unmatched) face crops for diagnostics; if False, never save; if blank, cameras inherit or fallback to script default.', null=True),
        ),
    ]
