# Generated by Django 5.2.5 on 2025-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('rtsp_url', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('scan_station', models.BooleanField(default=False)),
                ('script_type_default', models.PositiveSmallIntegerField(choices=[(1, 'FFmpeg'), (2, 'OpenCV')], default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
