# Generated by Django 5.2.5 on 2025-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cpu_affinity',
            field=models.CharField(blank=True, help_text='Comma-separated cores, e.g. "0,1"', max_length=64),
        ),
        migrations.AddField(
            model_name='camera',
            name='device',
            field=models.CharField(choices=[('cpu', 'CPU'), ('cuda', 'CUDA')], default='cpu', help_text='Intended ML device (for future OpenCV/CUDA path)', max_length=8),
        ),
        migrations.AddField(
            model_name='camera',
            name='gpu_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='hb_interval',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='camera',
            name='hwaccel',
            field=models.CharField(choices=[('none', 'none'), ('nvdec', 'nvdec')], default='none', help_text='FFmpeg hardware decode (nvdec => -hwaccel cuda)', max_length=8),
        ),
        migrations.AddField(
            model_name='camera',
            name='nice',
            field=models.SmallIntegerField(default=0, help_text='Process nice (-20..19)'),
        ),
        migrations.AddField(
            model_name='camera',
            name='rtsp_transport',
            field=models.CharField(choices=[('auto', 'auto'), ('tcp', 'tcp'), ('udp', 'udp')], default='auto', help_text='FFmpeg -rtsp_transport (tcp/udp/auto)', max_length=8),
        ),
        migrations.AddField(
            model_name='camera',
            name='snapshot_every',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
