# Generated by Django 5.2.5 on 2025-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_cpu_affinity_camera_device_camera_gpu_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='pause_until',
            field=models.DateTimeField(blank=True, help_text='Temporarily paused until this time', null=True),
        ),
    ]
