# Generated by Django 5.2.5 on 2025-08-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camera_pause_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='prefer_camera_over_profile',
            field=models.BooleanField(default=False, help_text='If enabled, Camera settings override StreamProfile (camera-first). Otherwise profile-first.'),
        ),
    ]
