# Generated by Django 5.2.5 on 2025-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_camera_prefer_camera_over_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='pause_until',
            field=models.DateTimeField(blank=True, help_text='If set, this camera will not launch until this time (Asia/Baghdad).', null=True),
        ),
    ]
