# Generated by Django 5.2.5 on 2025-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_alter_camera_pause_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='det_set_req',
            field=models.CharField(blank=True, help_text="Requested detector size, e.g. 'auto','640','800','1024','1600','2048' (nullable = use profile).", max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='target_fps_req',
            field=models.PositiveIntegerField(blank=True, help_text='Requested processed FPS for this camera (nullable = use profile).', null=True),
        ),
    ]
