# Generated by Django 5.2.5 on 2025-09-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_camera_det_set_req_camera_target_fps_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='cpu_affinity',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='device',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='gpu_index',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='hwaccel',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='nice',
        ),
    ]
