# Generated by Django 5.2.5 on 2025-09-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_dashboardtag_periodtemplate_usage_tags'),
        ('cameras', '0007_remove_camera_cpu_affinity_remove_camera_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='usage_tags',
            field=models.ManyToManyField(blank=True, help_text='Dashboards that should include this camera', related_name='cameras', to='attendance.dashboardtag'),
        ),
    ]
