# Generated by Django 5.2.5 on 2025-11-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_student_gender_alter_student_grade'),
        ('cameras', '0008_camera_usage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='period_templates',
            field=models.ManyToManyField(blank=True, help_text='If set, this camera only auto-runs when at least one of these periods has an active PeriodOccurrence covering the current time.', related_name='cameras', to='attendance.periodtemplate'),
        ),
    ]
