# Generated by Django 5.2.5 on 2026-07-04 13:16

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("currency", models.CharField(default="IQD", max_length=8)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_lists",
                        to="academics.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(db_index=True, max_length=64)),
                ("price_iqd", models.IntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "period_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Opaque scope key for the period context (e.g. 'lunch', 'term1').",
                        max_length=64,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricing_rules",
                        to="academics.grade",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="finance.pricelist",
                    ),
                ),
            ],
            options={
                "ordering": ["price_list__name", "product_code"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="IQD", max_length=8)),
                (
                    "balance_iqd",
                    models.IntegerField(
                        default=0,
                        help_text="Cached projection of the ledger. Always equals sum(transactions.amount_iqd).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "credit_limit_iqd",
                    models.IntegerField(
                        default=0,
                        help_text="Negative balance allowed down to -credit_limit (0 = no negative).",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet",
                        to="identity.person",
                    ),
                ),
            ],
            options={
                "ordering": ["person__code"],
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(db_index=True, max_length=64)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("price_base_iqd", models.IntegerField(default=0)),
                ("discount_iqd", models.IntegerField(default=0)),
                (
                    "discount_reason_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "discount_notes",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("final_charge_iqd", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("settled", "Settled"),
                            ("unpaid", "Unpaid"),
                            ("reversed", "Reversed"),
                            ("voided", "Voided"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("source_module", models.CharField(db_index=True, max_length=40)),
                (
                    "reference_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("reference_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_charges",
                        to="identity.person",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="finance.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("topup", "Top-up"),
                            ("debit", "Debit"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                            ("unpaid", "Unpaid"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "amount_iqd",
                    models.IntegerField(
                        help_text="Signed. +topup, -debit, +refund, +/-adjustment, 0 unpaid."
                    ),
                ),
                ("balance_before_iqd", models.IntegerField(default=0)),
                ("balance_after_iqd", models.IntegerField(default=0)),
                (
                    "source_module",
                    models.CharField(
                        db_index=True,
                        help_text="Originating domain, e.g. 'meal', 'tuition', 'manual_topup'.",
                        max_length=40,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("reference_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("is_reversal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_created_wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_created_wallet_transactions",
                        to="identity.staffprofile",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_transactions",
                        to="identity.person",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="finance.wallettransaction",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_iqd", models.IntegerField()),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "reason_notes",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("refunded_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_refunds",
                        to="identity.staffprofile",
                    ),
                ),
                (
                    "original_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="finance.charge",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_refunds",
                        to="identity.person",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="finance.wallet",
                    ),
                ),
                (
                    "settled_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settled_refunds",
                        to="finance.wallettransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-refunded_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_iqd", models.IntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank transfer"),
                            ("card", "Card"),
                            ("wallet_transfer", "Wallet transfer"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External receipt/transfer reference.",
                        max_length=128,
                    ),
                ),
                ("received_at", models.DateTimeField()),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_payments",
                        to="identity.person",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to="identity.staffprofile",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.wallet",
                    ),
                ),
                (
                    "settled_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settled_payments",
                        to="finance.wallettransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddField(
            model_name="charge",
            name="settled_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settled_charges",
                to="finance.wallettransaction",
            ),
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_iqd",
                    models.IntegerField(
                        help_text="Signed: positive = credit, negative = debit."
                    ),
                ),
                ("reason_code", models.CharField(db_index=True, max_length=32)),
                (
                    "reason_notes",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_adjustments",
                        to="identity.staffprofile",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_adjustments",
                        to="identity.person",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="finance.wallet",
                    ),
                ),
                (
                    "settled_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settled_adjustments",
                        to="finance.wallettransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pricelist",
            index=models.Index(
                fields=["is_active", "academic_year"],
                name="finance_pri_is_acti_93dd17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingrule",
            index=models.Index(
                fields=["product_code", "is_enabled"],
                name="finance_pri_product_c59f91_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingrule",
            index=models.Index(
                fields=["grade", "is_enabled"], name="finance_pri_grade_i_f87765_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pricingrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_iqd__gte", 0)),
                name="pricing_rule_price_non_negative",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricingrule",
            unique_together={("price_list", "product_code")},
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["status"], name="finance_wal_status_741ab4_idx"),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_limit_iqd__gte", 0)),
                name="wallet_credit_limit_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "balance_iqd__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("credit_limit_iqd"), "*", models.Value(-1)
                        ),
                    )
                ),
                name="wallet_balance_within_credit_limit",
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "created_at"], name="finance_wal_wallet__e9aa50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["person", "created_at"], name="finance_wal_person__c9474c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["source_module", "created_at"],
                name="finance_wal_source__89fe45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["tx_type", "created_at"], name="finance_wal_tx_type_875aca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["wallet", "refunded_at"], name="finance_ref_wallet__695b37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["original_charge", "refunded_at"],
                name="finance_ref_origina_d29c94_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_iqd__gt", 0)), name="refund_amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["wallet", "received_at"], name="finance_pay_wallet__5e6b82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["method", "received_at"], name="finance_pay_method_59d8e2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_iqd__gt", 0)),
                name="payment_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="charge",
            index=models.Index(
                fields=["person", "status"], name="finance_cha_person__22709a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="charge",
            index=models.Index(
                fields=["academic_year", "product_code"],
                name="finance_cha_academi_dec699_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="charge",
            index=models.Index(
                fields=["source_module", "status"],
                name="finance_cha_source__2168dc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="charge",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_base_iqd__gte", 0)),
                name="charge_price_base_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charge",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_iqd__gte", 0)),
                name="charge_discount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charge",
            constraint=models.CheckConstraint(
                condition=models.Q(("final_charge_iqd__gte", 0)),
                name="charge_final_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="charge",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_iqd__lte", models.F("price_base_iqd"))),
                name="charge_discount_within_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="charge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "final_charge_iqd__exact",
                        django.db.models.expressions.CombinedExpression(
                            models.F("price_base_iqd"), "-", models.F("discount_iqd")
                        ),
                    )
                ),
                name="charge_final_equals_price_minus_discount",
            ),
        ),
        migrations.AddIndex(
            model_name="adjustment",
            index=models.Index(
                fields=["wallet", "created_at"], name="finance_adj_wallet__f0bad8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adjustment",
            index=models.Index(
                fields=["reason_code", "created_at"],
                name="finance_adj_reason__d9c8d8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="adjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_iqd__exact", 0), _negated=True),
                name="adjustment_amount_nonzero",
            ),
        ),
    ]
