# Generated by Django 5.2.5 on 2026-07-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Primary', 'Secondary'.", max_length=100
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., '2026-2027'.", max_length=100),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Natural key used by other models and imports, e.g., '2026-27'.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="At most one active academic year per school (enforced at DB level).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="academic_year_end_after_start",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="academic_year_single_active",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., 'Grade 1'.", max_length=100),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Natural key for imports and FK references, e.g., 'G1'.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades",
                        to="academics.schoollevel",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., 'Section A'.", max_length=100),
                ),
                ("code", models.CharField(help_text="e.g., 'A'.", max_length=32)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year-specific. Enforced in StudentEnrollment.clean().",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="academics.grade",
                    ),
                ),
                (
                    "homeroom_adviser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advised_sections",
                        to="identity.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["academic_year__start_date", "grade__order", "code"],
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("withdrawal_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("future", "Future"),
                            ("transferred", "Transferred"),
                            ("withdrawn", "Withdrawn"),
                            ("graduated", "Graduated"),
                            ("repeated", "Repeated"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="academics.grade",
                    ),
                ),
                (
                    "prior_enrollment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The enrollment this one continues from (transfer/repeat).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subsequent",
                        to="academics.studentenrollment",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="academics.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="identity.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year__start_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollmentSectionPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_placements",
                        to="academics.studentenrollment",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="academics.section",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["academic_year", "grade", "is_active"],
                name="academics_s_academi_e6453e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("academic_year", "grade", "code")},
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["academic_year", "status"],
                name="academics_s_academi_d1e8be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["grade", "section", "status"],
                name="academics_s_grade_i_4d2577_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["student", "status"], name="academics_s_student_7ca871_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("student", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="studentenrollmentsectionplacement",
            index=models.Index(
                fields=["enrollment", "is_current"],
                name="academics_s_enrollm_c28139_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollmentsectionplacement",
            index=models.Index(
                fields=["section", "is_current"], name="academics_s_section_009e26_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentenrollmentsectionplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_current", False), ("end_date__isnull", True), _connector="OR"
                ),
                name="placement_current_has_no_end_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentenrollmentsectionplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("enrollment",),
                name="placement_single_current_per_enrollment",
            ),
        ),
    ]
