# Generated by Django 5.2.5 on 2026-07-03 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0031_alter_mealsubscription_plan_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("middle_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="person_photos/")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RoleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("staff", "Staff"),
                            ("teacher", "Teacher"),
                            ("parent", "Parent"),
                            ("guardian", "Guardian"),
                            ("guest", "Guest"),
                            ("vendor", "Vendor"),
                            ("administrator", "Administrator"),
                            ("finance", "Finance"),
                            ("hr", "HR"),
                            ("principal", "Principal"),
                            ("vice_principal", "Vice Principal"),
                            ("librarian", "Librarian"),
                            ("nurse", "Nurse"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="staff_profile",
                        serialize=False,
                        to="identity.person",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Staff code assigned by the school.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("is_teacher", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["person__code"],
            },
        ),
        migrations.CreateModel(
            name="PersonRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="identity.person",
                    ),
                ),
                (
                    "role_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_roles",
                        to="identity.roletype",
                    ),
                ),
            ],
            options={
                "ordering": ["person", "role_type"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student_profile",
                        serialize=False,
                        to="identity.person",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Student code assigned by the school.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Transitional compatibility field for legacy attendance.Student grade data.",
                        max_length=50,
                    ),
                ),
                ("homeroom", models.CharField(blank=True, max_length=50)),
                (
                    "has_meal",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Transitional compatibility field for legacy attendance.Student meal data.",
                    ),
                ),
                (
                    "has_bus",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Transitional compatibility field for legacy attendance.Student bus data.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migrated_to",
                        to="attendance.student",
                    ),
                ),
            ],
            options={
                "ordering": ["person__code"],
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["is_active"], name="identity_pe_is_acti_4605b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="identity_pe_last_na_0cebd7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personrole",
            index=models.Index(
                fields=["person", "is_active"], name="identity_pe_person__b60bd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personrole",
            index=models.Index(
                fields=["role_type", "is_active"], name="identity_pe_role_ty_305595_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personrole",
            unique_together={("person", "role_type")},
        ),
    ]
