# Generated by Django 5.2.5 on 2026-07-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lunch", "Lunch"),
                            ("breakfast", "Breakfast"),
                            ("snack", "Snack"),
                        ],
                        db_index=True,
                        default="lunch",
                        max_length=20,
                    ),
                ),
                (
                    "period_template_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Source tag for the generic period-template reference (e.g. 'attendance'). Blank when no period template is linked.",
                        max_length=20,
                    ),
                ),
                (
                    "period_template_ref_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Generic period-template reference id. Used together with period_template_source to identify the underlying timetable period without a typed FK.",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional display override, e.g. 'First lunch block'.",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["kind", "is_active"], name="meals_mealp_kind_e50bc2_idx"
                    ),
                    models.Index(
                        fields=["period_template_source", "period_template_ref_id"],
                        name="meals_mealp_period__d81c0a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("period_template_ref_id__isnull", False)),
                        fields=(
                            "kind",
                            "period_template_source",
                            "period_template_ref_id",
                        ),
                        name="meal_period_unique_kind_and_template_ref",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lunch", "Lunch"),
                            ("breakfast", "Breakfast"),
                            ("snack", "Snack"),
                        ],
                        db_index=True,
                        default="lunch",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("date_range", "Date-range"), ("wallet", "Wallet")],
                        db_index=True,
                        default="date_range",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("allow_supervisor_confirm", models.BooleanField(default=True)),
                ("allow_supervisor_unconfirm", models.BooleanField(default=False)),
                ("allow_supervisor_refund", models.BooleanField(default=False)),
                ("require_reason_on_override", models.BooleanField(default=True)),
                ("require_reason_on_unconfirm", models.BooleanField(default=False)),
                ("require_reason_on_refund", models.BooleanField(default=True)),
                (
                    "insufficient_funds_mode",
                    models.CharField(
                        choices=[
                            ("deny", "Deny"),
                            ("allow_unpaid", "Allow unpaid"),
                            ("allow_negative", "Allow negative"),
                        ],
                        default="deny",
                        max_length=20,
                    ),
                ),
                (
                    "credit_limit_iqd",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Only used when mode=Wallet and insufficient-funds mode = Allow negative. Blank = no negative limit.",
                        null=True,
                    ),
                ),
                (
                    "default_price_iqd",
                    models.IntegerField(
                        default=0,
                        help_text="Fallback base price (IQD) when no period or person override matches.",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["kind", "is_active"], name="meals_mealp_kind_f7ad55_idx"
                    ),
                    models.Index(
                        fields=["mode", "is_active"], name="meals_mealp_mode_13f9ab_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("default_price_iqd__gte", 0)),
                        name="meal_plan_default_price_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MealPersonPriceOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_iqd", models.IntegerField(default=0)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank = applies to all periods of this plan.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_price_overrides",
                        to="meals.mealperiod",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_price_overrides",
                        to="identity.person",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_price_overrides",
                        to="meals.mealplan",
                    ),
                ),
            ],
            options={
                "ordering": ["person", "meal_plan", "meal_period__sort_order"],
                "indexes": [
                    models.Index(
                        fields=["person", "is_enabled"],
                        name="meals_mealp_person__67b790_idx",
                    ),
                    models.Index(
                        fields=["meal_plan", "is_enabled"],
                        name="meals_mealp_meal_pl_3d47ce_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price_iqd__gte", 0)),
                        name="meal_person_price_override_non_negative",
                    ),
                    models.UniqueConstraint(
                        fields=("person", "meal_plan", "meal_period"),
                        name="meal_person_override_unique_per_plan_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_until__isnull", True),
                            ("effective_from__isnull", True),
                            ("effective_until__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="meal_person_override_effective_window_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MealPeriodPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_iqd", models.IntegerField(default=0)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_prices",
                        to="meals.mealperiod",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_prices",
                        to="meals.mealplan",
                    ),
                ),
            ],
            options={
                "ordering": ["meal_plan__name", "meal_period__sort_order"],
                "indexes": [
                    models.Index(
                        fields=["meal_plan", "is_enabled"],
                        name="meals_mealp_meal_pl_213c5f_idx",
                    ),
                    models.Index(
                        fields=["meal_period", "is_enabled"],
                        name="meals_mealp_meal_pe_3dd3bd_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price_iqd__gte", 0)),
                        name="meal_period_price_non_negative",
                    )
                ],
                "unique_together": {("meal_plan", "meal_period")},
            },
        ),
    ]
