# Generated by Django 5.2.5 on 2026-07-05 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("identity", "0001_initial"),
        ("meals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("future", "Future"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                (
                    "plan_type",
                    models.CharField(
                        default="monthly",
                        help_text="Reporting label (annual/monthly/other). Does not drive charging.",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(db_index=True, default="manual", max_length=40),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=1,
                        help_text="Order number. Lower = higher priority = evaluated first. 1=primary, 2=fallback. Same-priority overlapping ACTIVE subscriptions for the same person are rejected.",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_subscriptions",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="meals.mealplan",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_subscriptions",
                        to="identity.person",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_subscriptions",
                        to="identity.staffprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_subscriptions",
                        to="identity.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["person", "priority", "start_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="MealEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("eligible", "Eligible"),
                            ("not_eligible", "Not eligible"),
                            ("overridden_eligible", "Overridden eligible"),
                            ("overridden_denied", "Overridden denied"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "grade_code_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "section_code_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "absence_reason",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "reason_notes",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eligibilities",
                        to="meals.mealplan",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_eligibilities",
                        to="identity.person",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_meal_eligibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_eligibilities",
                        to="identity.studentprofile",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eligibilities",
                        to="meals.mealsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MealException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("one_time_eligible", "One-time eligible"),
                            ("temporary_deny", "Temporary deny"),
                            ("guest_eligible", "Guest eligible"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("effective_date", models.DateField(db_index=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional. Blank = single-day exception (effective_date only).",
                        null=True,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "reason_notes",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_meal_exceptions",
                        to="identity.staffprofile",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions",
                        to="meals.mealplan",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_exceptions",
                        to="identity.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["person", "effective_date"],
                        name="meals_meale_person__38fa35_idx",
                    ),
                    models.Index(
                        fields=["kind", "is_active"], name="meals_meale_kind_22a959_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("effective_date")),
                            _connector="OR",
                        ),
                        name="meal_exception_end_after_effective",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mealsubscription",
            index=models.Index(
                fields=["person", "status", "start_date", "end_date"],
                name="meals_meals_person__fa5dfc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mealsubscription",
            index=models.Index(
                fields=["student", "status"], name="meals_meals_student_e1dbe4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealsubscription",
            index=models.Index(
                fields=["staff", "status"], name="meals_meals_staff_i_1a8c7b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="meal_subscription_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", 1)),
                name="meal_subscription_priority_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="mealeligibility",
            index=models.Index(
                fields=["date", "decision"], name="meals_meale_date_85b8c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealeligibility",
            index=models.Index(
                fields=["person", "date"], name="meals_meale_person__309125_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealeligibility",
            index=models.Index(
                fields=["student", "date"], name="meals_meale_student_56ae03_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealeligibility",
            unique_together={("person", "date")},
        ),
    ]
