# Generated by Django 5.2.5 on 2026-07-05 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0031_alter_mealsubscription_plan_type"),
        ("finance", "0001_initial"),
        ("identity", "0001_initial"),
        ("meals", "0002_mealsubscription_mealeligibility_mealexception_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealServiceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("denied", "Denied"),
                            ("unpaid", "Unpaid"),
                            ("refunded", "Refunded"),
                            ("voided", "Voided"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("price_base_iqd", models.IntegerField(default=0)),
                ("price_override_iqd", models.IntegerField(default=0)),
                ("discount_iqd", models.IntegerField(default=0)),
                ("final_charge_iqd", models.IntegerField(default=0)),
                (
                    "price_resolution_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which rule won: 'period_price' / 'person_override' / 'default' / 'date_range_no_charge'.",
                        max_length=32,
                    ),
                ),
                ("wallet_balance_before_iqd", models.IntegerField(default=0)),
                ("wallet_balance_after_iqd", models.IntegerField(default=0)),
                (
                    "grade_code_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "section_code_snapshot",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "meal_period_label_snapshot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "reason_notes",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "served_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eligibility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_events",
                        to="meals.mealeligibility",
                    ),
                ),
                (
                    "meal_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_events",
                        to="meals.mealperiod",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_events",
                        to="meals.mealplan",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_service_events",
                        to="identity.person",
                    ),
                ),
                (
                    "recognition_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_service_events",
                        to="attendance.attendanceevent",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_meal_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "served_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="served_meal_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_service_events",
                        to="identity.staffprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_service_events",
                        to="identity.studentprofile",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_events",
                        to="meals.mealsubscription",
                    ),
                ),
                (
                    "wallet_refund_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_refund_events",
                        to="finance.wallettransaction",
                    ),
                ),
                (
                    "wallet_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_service_events",
                        to="finance.wallettransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MealSupervisorAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("confirm", "Confirm"),
                            ("unconfirm", "Unconfirm"),
                            ("deny", "Deny"),
                            ("refund", "Refund"),
                            ("void", "Void"),
                            ("override_eligible", "Override (eligible)"),
                            ("override_denied", "Override (denied)"),
                            ("manual_lookup", "Manual lookup"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "reason_notes",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eligibility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_actions",
                        to="meals.mealeligibility",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_supervisor_actions",
                        to="identity.staffprofile",
                    ),
                ),
                (
                    "performed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_supervisor_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_actions",
                        to="meals.mealserviceevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mealserviceevent",
            index=models.Index(
                fields=["date", "status"], name="meals_meals_date_abf6be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealserviceevent",
            index=models.Index(
                fields=["person", "date"], name="meals_meals_person__0440a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealserviceevent",
            index=models.Index(
                fields=["student", "date"], name="meals_meals_student_c5f47b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealserviceevent",
            index=models.Index(
                fields=["section_code_snapshot", "date"],
                name="meals_meals_section_8db409_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mealserviceevent",
            index=models.Index(
                fields=["meal_plan", "date"], name="meals_meals_meal_pl_2d1292_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealserviceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("final_charge_iqd__gte", 0)),
                name="meal_service_event_final_charge_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealserviceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_base_iqd__gte", 0)),
                name="meal_service_event_price_base_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealserviceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_iqd__gte", 0)),
                name="meal_service_event_discount_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="mealsupervisoraction",
            index=models.Index(
                fields=["service_event", "performed_at"],
                name="meals_meals_service_b28dd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mealsupervisoraction",
            index=models.Index(
                fields=["action", "performed_at"], name="meals_meals_action_f2861d_idx"
            ),
        ),
    ]
