# Generated by Django 5.2.5 on 2026-04-15 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('random', 'Completely Random'), ('rigged', 'Rigged / Controlled')], default='random', max_length=20)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('auto', 'Auto')], default='dark', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('live', 'Live'), ('done', 'Done')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_draw_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('draw_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='match_draw.drawevent')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('draw_event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DrawSpinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_number', models.PositiveIntegerField()),
                ('was_forced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_logs', to='match_draw.drawevent')),
                ('selected_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_logs', to='match_draw.drawteam')),
            ],
            options={
                'ordering': ['spin_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DrawMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_order', models.PositiveIntegerField(default=1)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('draw_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='match_draw.drawevent')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_1', to='match_draw.drawteam')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_2', to='match_draw.drawteam')),
            ],
            options={
                'ordering': ['match_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DrawPairRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_rules', to='match_draw.drawevent')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_rule_as_a', to='match_draw.drawteam')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_rule_as_b', to='match_draw.drawteam')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('draw_event', 'team_a'), name='unique_pair_rule_team_a_per_event'), models.UniqueConstraint(fields=('draw_event', 'team_b'), name='unique_pair_rule_team_b_per_event')],
            },
        ),
    ]
