# Generated by Django 5.2.5 on 2026-07-01 17:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('attendance', '0001_initial'), ('attendance', '0002_recognitionsettings_max_periods_per_day'), ('attendance', '0003_alter_periodtemplate_early_grace_minutes_and_more'), ('attendance', '0004_remove_student_full_name_student_first_name_and_more'), ('attendance', '0005_faceembedding_arcface_model_and_more'), ('attendance', '0006_faceembedding_uniq_active_embedding_per_student'), ('attendance', '0007_faceembedding_attendance__embeddi_68477a_idx_and_more'), ('attendance', '0008_alter_faceembedding_arcface_model_and_more'), ('attendance', '0009_faceembedding_used_images_detail'), ('attendance', '0010_faceembedding_last_used_min_score'), ('attendance', '0011_faceembedding_avg_used_score'), ('attendance', '0012_alter_attendanceevent_ts'), ('attendance', '0013_recognitionsettings_min_face_px'), ('attendance', '0014_alter_recognitionsettings_min_face_px'), ('attendance', '0015_recognitionsettings_changed_at'), ('attendance', '0016_alter_attendanceevent_crop_path_and_more'), ('attendance', '0017_attendancerecord_last_pass_at_and_more'), ('attendance', '0018_recognitionsettings_crops_apply_all_students_and_more'), ('attendance', '0019_faceembedding_crops_opt_in'), ('attendance', '0020_attendancerecord_confirmed_and_more'), ('attendance', '0021_dashboardtag_periodtemplate_usage_tags')]

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('cameras', '0005_alter_camera_pause_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekdays_mask', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('early_grace_minutes', models.PositiveSmallIntegerField(default=0)),
                ('late_grace_minutes', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.FloatField(default=0.75)),
                ('re_register_window_sec', models.PositiveIntegerField(default=10)),
                ('min_improve_delta', models.FloatField(default=0.01)),
                ('delete_old_cropped', models.BooleanField(default=False)),
                ('save_all_crops', models.BooleanField(default=False)),
                ('use_cosine_similarity', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_code', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('is_school_day', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='attendance.periodtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('best_seen', models.DateTimeField()),
                ('best_score', models.FloatField()),
                ('best_crop', models.CharField(blank=True, default='', max_length=300)),
                ('sightings', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='present', max_length=16)),
                ('best_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.camera')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.periodoccurrence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('score', models.FloatField()),
                ('crop_path', models.CharField(blank=True, default='', max_length=300)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.camera')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.periodoccurrence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='periodoccurrence',
            index=models.Index(fields=['date', 'start_dt', 'end_dt'], name='attendance__date_b87a52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodoccurrence',
            unique_together={('template', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'period'], name='attendance__student_00c8c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'period')},
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='early_grace_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Extend the start earlier by this many minutes when generating the daily window.'),
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='end_time',
            field=models.TimeField(help_text='Local end time of the period (HH:MM).'),
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='If off, this template is ignored when generating daily occurrences.'),
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='late_grace_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Extend the end later by this many minutes when generating the daily window.'),
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='name',
            field=models.CharField(help_text="Display name for this period (e.g., 'First Block').", max_length=64),
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Sort order within the day. Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='start_time',
            field=models.TimeField(help_text='Local start time of the period (HH:MM).'),
        ),
        migrations.AlterField(
            model_name='periodtemplate',
            name='weekdays_mask',
            field=models.PositiveSmallIntegerField(default=31, help_text='Bitmask of active weekdays. Add the values for the days you want:\nMon=1, Tue=2, Wed=4, Thu=8, Fri=16, Sat=32, Sun=64. ALL=127.\nExamples:\n• Mon–Fri: 31  (1+2+4+8+16)\n• Sat+Sun (western weekend): 96  (32+64)\n• Fri+Sat (Gulf weekend): 48  (16+32)\n• Sun–Thu (Fri & Sat OFF): 79  (64+1+2+4+8)\n• Only Sun: 64  • Only Fri: 16\nAt runtime we test: mask & (1 << date.weekday()).'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='Given name.', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Family name / surname.', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text='Middle name(s), if any.', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='crop_path',
            field=models.CharField(blank=True, default='', help_text='MEDIA-relative path of the face crop saved for this event (if any).', max_length=300),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='score',
            field=models.FloatField(help_text='Similarity score for this event (0.00–1.00; higher means more similar to the enrolled embedding).'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='ts',
            field=models.DateTimeField(help_text='Timestamp (timezone-aware) when this event was generated.'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='best_crop',
            field=models.CharField(blank=True, default='', help_text='MEDIA-relative path of the best face crop for this record.', max_length=300),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='best_score',
            field=models.FloatField(help_text='Highest similarity score observed during this record’s time window.'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='sightings',
            field=models.PositiveIntegerField(default=1, help_text='How many frames contributed to this record (debounced within the window).'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(default='present', help_text='Computed attendance status for the period (e.g., present/late/absent).', max_length=16),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, help_text='Auto-updated change marker. Runners poll this field and hot-reload settings within a few seconds after you save.'),
        ),
        migrations.AlterField(
            model_name='recognitionsettings',
            name='delete_old_cropped',
            field=models.BooleanField(default=False, help_text='If ON, old cropped face images will be deleted automatically to save disk space. Turn OFF if you need to keep historical crops for audit/debug.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='max_periods_per_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional cap on how many periods can count as ‘present’ per student per day. Leave blank for no limit. Example: 1 = only the first recognized period counts.', null=True),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='min_face_px',
            field=models.PositiveIntegerField(default=40, help_text='Reject faces smaller than this many pixels (shortest side of the face bounding box) before scoring. Use this to control the ‘working distance’: higher = requires closer/bigger faces (fewer false accepts), lower = allows farther/smaller faces (more recalls). Guideline for 1440p streams: 36–48 px ≈ ~4–6 m with good optics/bitrate.'),
        ),
        migrations.AlterField(
            model_name='recognitionsettings',
            name='min_improve_delta',
            field=models.FloatField(default=0.01, help_text='Within the debounce window, only update best_seen if the new score improves the previous best by at least this amount. Example: 0.02 avoids churn from tiny score fluctuations.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='recognitionsettings',
            name='min_score',
            field=models.FloatField(default=0.75, help_text='Minimum similarity score (0.00–1.00) required to accept a match. Raise this to reduce false accepts; lower it to recognize faces at longer distances or in poor lighting. Typical range: 0.50–0.85. Default 0.75.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='recognitionsettings',
            name='re_register_window_sec',
            field=models.PositiveIntegerField(default=10, help_text='Debounce window in seconds per student. During this window, repeated detections of the same person on the same camera/period will not create new records; we only update last_seen/best_seen. Prevents duplicate ‘pops’ when a person stays in view.'),
        ),
        migrations.AlterField(
            model_name='recognitionsettings',
            name='save_all_crops',
            field=models.BooleanField(default=False, help_text='If ON, save every detected face crop (matched and unmatched). Useful for tuning but increases disk usage and I/O. If OFF, only matched/best crops are saved.'),
        ),
        migrations.AlterField(
            model_name='recognitionsettings',
            name='use_cosine_similarity',
            field=models.BooleanField(default=True, help_text='Similarity metric preference. Cosine similarity (ON) is the default and recommended. Note: current runtime uses cosine regardless; this flag is reserved for future switching.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='h_code',
            field=models.CharField(help_text='Human/School code (unique student identifier, e.g., H123456).', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='last_pass_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='pass_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, choices=[('KG1', 'Kindergarten 1'), ('KG2', 'Kindergarten 2'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5'), ('G6', 'Grade 6'), ('G7', 'Grade 7'), ('G8', 'Grade 8'), ('G9', 'Grade 9'), ('G10', 'Grade 10'), ('G11', 'Grade 11'), ('G12', 'Grade 12')], db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_bus',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='has_lunch',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_apply_all_students',
            field=models.BooleanField(default=False, help_text='If ON, capture applies to ALL students. If OFF, only FaceEmbeddings with per-student opt-in.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_enabled',
            field=models.BooleanField(default=False, help_text='Master switch. If off, no per-student capture occurs.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_format',
            field=models.CharField(default='png', help_text='png or jpg', max_length=8),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_include_period',
            field=models.BooleanField(default=True, help_text='Insert /<period_id>/ between date and camera in the path.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_keep_n',
            field=models.PositiveIntegerField(default=5, help_text='Keep only the top-N images per (date/period/camera) folder.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_margin',
            field=models.PositiveIntegerField(default=8, help_text='Optional black margin/border in saved image.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_padding',
            field=models.PositiveIntegerField(default=16, help_text='Extra pixels around face before saving (visual pad).'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_quality',
            field=models.PositiveIntegerField(default=95, help_text='If JPG, 1..100'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_save_threshold',
            field=models.FloatField(default=0.65, help_text='Archive when live match score ≥ this value (independent of recognition min-score).'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_subdir',
            field=models.CharField(default='captures', help_text="Subfolder under each student’s gallery (e.g., 'captures').", max_length=32),
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim', models.PositiveSmallIntegerField(default=512, help_text='Embedding dimensionality. We use 512 for ArcFace.')),
                ('vector', models.BinaryField(help_text='L2‑normalized embedding stored as raw float32 bytes (length = dim*4).')),
                ('source_path', models.CharField(blank=True, help_text='MEDIA‑relative path for reference (e.g., saved .npy for this vector).', max_length=512)),
                ('is_active', models.BooleanField(default=True, help_text='Exactly one active embedding per student (enforced by DB constraint).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp.')),
                ('camera', models.ForeignKey(blank=True, help_text='Camera associated with this embedding, if known (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.camera')),
                ('student', models.ForeignKey(help_text='The student this embedding belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='attendance.student')),
                ('arcface_model', models.CharField(blank=True, default='buffalo_l', help_text='InsightFace/ArcFace model name used to generate this embedding.', max_length=64)),
                ('avg_brightness', models.FloatField(default=0.0, help_text='Mean grayscale intensity 0–255 across used images.')),
                ('avg_sharpness', models.FloatField(default=0.0, help_text='Mean Laplacian variance across used images (higher ≈ sharper).')),
                ('embedding_norm', models.FloatField(default=0.0, help_text='L2 norm of the stored vector (should be ~1.0).')),
                ('embedding_sha256', models.CharField(blank=True, default='', help_text='SHA‑256 hash of the raw float32 bytes (useful for dedup/versioning).', max_length=64)),
                ('enroll_notes', models.TextField(blank=True, default='', help_text='Concise human‑readable one‑liner: k, det, counts, provider, norm, sample files.')),
                ('enroll_runtime_ms', models.PositiveIntegerField(default=0, help_text='End‑to‑end enrollment runtime in milliseconds.')),
                ('images_considered', models.PositiveIntegerField(default=0, help_text='Total gallery images discovered for the student at enrollment time.')),
                ('images_used', models.PositiveIntegerField(default=0, help_text='Images actually used after filtering/scoring.')),
                ('last_enrolled_at', models.DateTimeField(blank=True, help_text='When this embedding was (re)computed.', null=True)),
                ('last_used_det_size', models.PositiveIntegerField(default=640, help_text='Face detector input size (square). Higher can help small faces but costs GPU.')),
                ('last_used_k', models.PositiveIntegerField(default=0, help_text='How many images were averaged to build this vector.')),
                ('provider', models.CharField(blank=True, default='CUDAExecutionProvider', help_text='ONNX Runtime execution provider actually used (CUDA or CPU).', max_length=64)),
                ('used_images', models.JSONField(blank=True, default=list, help_text='Filenames of images included in the K‑image average.')),
                ('used_images_detail', models.JSONField(blank=True, default=list, help_text="List of objects for the K images actually used: [{'name': 'H123456_1.jpg', 'score': 0.93, 'sharp': 123.4, 'bright': 108.7}, ...]. Score is the combined ranking value used to pick top‑K.")),
                ('last_used_min_score', models.FloatField(blank=True, help_text='Minimum quality score threshold (0..1) used for the last enrollment.', null=True)),
                ('avg_used_score', models.FloatField(default=0.0, help_text='Mean of the per-image ROI quality scores (0..1) for the images used to build the .npy.')),
                ('crops_opt_in', models.BooleanField(default=False, help_text='If true and global capture is enabled, archive top crops for this student.')),
            ],
            options={
                'indexes': [models.Index(fields=['student'], name='attendance__student_988459_idx'), models.Index(fields=['is_active', 'dim'], name='attendance__is_acti_72849d_idx'), models.Index(fields=['created_at'], name='attendance__created_12aa0a_idx'), models.Index(fields=['embedding_sha256'], name='attendance__embeddi_68477a_idx'), models.Index(fields=['last_enrolled_at'], name='attendance__last_en_fcf191_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='uniq_active_embedding_per_student')],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='confirmed',
            field=models.BooleanField(db_index=True, default=False, help_text='Manually marked by a lunch supervisor as verified.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='pass_gap_window_sec',
            field=models.PositiveIntegerField(default=120, help_text='Gap in seconds to count a *new pass* for pass_count. Used to increment AttendanceRecord.pass_count when the same student reappears after this gap within the same period. Typical 60–240.We meant to use it for the LUNCH periods for the student waiting in queue, e.x. lunch-pri & lunch-sec'),
        ),
        migrations.CreateModel(
            name='DashboardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(choices=[('lunch', 'Lunch'), ('bus', 'Bus'), ('assembly', 'Assembly')], max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Dashboard tag',
                'verbose_name_plural': 'Dashboard tags',
            },
        ),
        migrations.AddField(
            model_name='periodtemplate',
            name='usage_tags',
            field=models.ManyToManyField(blank=True, help_text='Dashboards that should include this period', related_name='period_templates', to='attendance.dashboardtag'),
        ),
    ]
