# Generated by Django 5.2.5 on 2025-08-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekdays_mask', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('early_grace_minutes', models.PositiveSmallIntegerField(default=0)),
                ('late_grace_minutes', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.FloatField(default=0.75)),
                ('re_register_window_sec', models.PositiveIntegerField(default=10)),
                ('min_improve_delta', models.FloatField(default=0.01)),
                ('delete_old_cropped', models.BooleanField(default=False)),
                ('save_all_crops', models.BooleanField(default=False)),
                ('use_cosine_similarity', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_code', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('is_school_day', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='attendance.periodtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('best_seen', models.DateTimeField()),
                ('best_score', models.FloatField()),
                ('best_crop', models.CharField(blank=True, default='', max_length=300)),
                ('sightings', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='present', max_length=16)),
                ('best_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.camera')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.periodoccurrence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('score', models.FloatField()),
                ('crop_path', models.CharField(blank=True, default='', max_length=300)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.camera')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.periodoccurrence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='periodoccurrence',
            index=models.Index(fields=['date', 'start_dt', 'end_dt'], name='attendance__date_b87a52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodoccurrence',
            unique_together={('template', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'period'], name='attendance__student_00c8c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'period')},
        ),
    ]
