# Generated by Django 5.2.5 on 2025-08-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionsettings',
            name='max_periods_per_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="If set, cap how many periods can count as 'present' per student per day.", null=True),
        ),
    ]
