# Generated by Django 5.2.5 on 2025-08-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_student_full_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='arcface_model',
            field=models.CharField(blank=True, default='buffalo_l', max_length=64),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='avg_brightness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='avg_sharpness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='embedding_norm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='embedding_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='enroll_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='enroll_runtime_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='images_considered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='images_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='last_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='last_used_det_size',
            field=models.PositiveIntegerField(default=640),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='last_used_k',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='provider',
            field=models.CharField(blank=True, default='CUDAExecutionProvider', max_length=64),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='used_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
