# Generated by Django 5.2.5 on 2025-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_faceembedding_arcface_model_and_more'),
        ('cameras', '0005_alter_camera_pause_until'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='faceembedding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='uniq_active_embedding_per_student'),
        ),
    ]
