# Generated by Django 5.2.5 on 2025-08-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_faceembedding_uniq_active_embedding_per_student'),
        ('cameras', '0005_alter_camera_pause_until'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['embedding_sha256'], name='attendance__embeddi_68477a_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['last_enrolled_at'], name='attendance__last_en_fcf191_idx'),
        ),
    ]
