# Generated by Django 5.2.5 on 2025-08-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_faceembedding_attendance__embeddi_68477a_idx_and_more'),
        ('cameras', '0005_alter_camera_pause_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceembedding',
            name='arcface_model',
            field=models.CharField(blank=True, default='buffalo_l', help_text='InsightFace/ArcFace model name used to generate this embedding.', max_length=64),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='avg_brightness',
            field=models.FloatField(default=0.0, help_text='Mean grayscale intensity 0–255 across used images.'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='avg_sharpness',
            field=models.FloatField(default=0.0, help_text='Mean Laplacian variance across used images (higher ≈ sharper).'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='camera',
            field=models.ForeignKey(blank=True, help_text='Camera associated with this embedding, if known (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.camera'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Row creation timestamp.'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='dim',
            field=models.PositiveSmallIntegerField(default=512, help_text='Embedding dimensionality. We use 512 for ArcFace.'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='embedding_norm',
            field=models.FloatField(default=0.0, help_text='L2 norm of the stored vector (should be ~1.0).'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='embedding_sha256',
            field=models.CharField(blank=True, default='', help_text='SHA‑256 hash of the raw float32 bytes (useful for dedup/versioning).', max_length=64),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='enroll_notes',
            field=models.TextField(blank=True, default='', help_text='Concise human‑readable one‑liner: k, det, counts, provider, norm, sample files.'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='enroll_runtime_ms',
            field=models.PositiveIntegerField(default=0, help_text='End‑to‑end enrollment runtime in milliseconds.'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='images_considered',
            field=models.PositiveIntegerField(default=0, help_text='Total gallery images discovered for the student at enrollment time.'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='images_used',
            field=models.PositiveIntegerField(default=0, help_text='Images actually used after filtering/scoring.'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Exactly one active embedding per student (enforced by DB constraint).'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='last_enrolled_at',
            field=models.DateTimeField(blank=True, help_text='When this embedding was (re)computed.', null=True),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='last_used_det_size',
            field=models.PositiveIntegerField(default=640, help_text='Face detector input size (square). Higher can help small faces but costs GPU.'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='last_used_k',
            field=models.PositiveIntegerField(default=0, help_text='How many images were averaged to build this vector.'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='provider',
            field=models.CharField(blank=True, default='CUDAExecutionProvider', help_text='ONNX Runtime execution provider actually used (CUDA or CPU).', max_length=64),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='source_path',
            field=models.CharField(blank=True, help_text='MEDIA‑relative path for reference (e.g., saved .npy for this vector).', max_length=512),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='student',
            field=models.ForeignKey(help_text='The student this embedding belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='used_images',
            field=models.JSONField(blank=True, default=list, help_text='Filenames of images included in the K‑image average.'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='vector',
            field=models.BinaryField(help_text='L2‑normalized embedding stored as raw float32 bytes (length = dim*4).'),
        ),
    ]
