# Generated by Django 5.2.5 on 2025-08-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_faceembedding_arcface_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='used_images_detail',
            field=models.JSONField(blank=True, default=list, help_text="List of objects for the K images actually used: [{'name': 'H123456_1.jpg', 'score': 0.93, 'sharp': 123.4, 'bright': 108.7}, ...]. Score is the combined ranking value used to pick top‑K."),
        ),
    ]
