# Generated by Django 5.2.5 on 2025-08-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_faceembedding_used_images_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='last_used_min_score',
            field=models.FloatField(blank=True, help_text='Minimum quality score threshold (0..1) used for the last enrollment.', null=True),
        ),
    ]
