# Generated by Django 5.2.5 on 2025-08-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_faceembedding_last_used_min_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='avg_used_score',
            field=models.FloatField(default=0.0, help_text='Mean of the per-image ROI quality scores (0..1) for the images used to build the .npy.'),
        ),
    ]
