# Generated by Django 5.2.5 on 2025-09-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_faceembedding_avg_used_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='ts',
            field=models.DateTimeField(help_text='The timestamp of the event where it was taken.'),
        ),
    ]
