# Generated by Django 5.2.5 on 2025-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_recognitionsettings_min_face_px'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionsettings',
            name='min_face_px',
            field=models.PositiveIntegerField(default=40, help_text='Drop faces smaller than this many pixels on the shortest bbox side. (ex. like 36px to have maximum up to 5m distance for recognitions.)'),
        ),
    ]
