# Generated by Django 5.2.5 on 2025-09-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_recognitionsettings_min_face_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionsettings',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, help_text='Bumps on every save to notify runners.'),
        ),
    ]
