# Generated by Django 5.2.5 on 2025-09-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_attendanceevent_crop_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='last_pass_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='pass_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, choices=[('KG1', 'Kindergarten 1'), ('KG2', 'Kindergarten 2'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5'), ('G6', 'Grade 6'), ('G7', 'Grade 7'), ('G8', 'Grade 8'), ('G9', 'Grade 9'), ('G10', 'Grade 10'), ('G11', 'Grade 11'), ('G12', 'Grade 12')], db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_bus',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='has_lunch',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
