# Generated by Django 5.2.5 on 2025-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_attendancerecord_last_pass_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_apply_all_students',
            field=models.BooleanField(default=False, help_text='If ON, capture applies to ALL students. If OFF, only FaceEmbeddings with per-student opt-in.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_enabled',
            field=models.BooleanField(default=False, help_text='Master switch. If off, no per-student capture occurs.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_format',
            field=models.CharField(default='png', help_text='png or jpg', max_length=8),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_include_period',
            field=models.BooleanField(default=True, help_text='Insert /<period_id>/ between date and camera in the path.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_keep_n',
            field=models.PositiveIntegerField(default=5, help_text='Keep only the top-N images per (date/period/camera) folder.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_margin',
            field=models.PositiveIntegerField(default=8, help_text='Optional black margin/border in saved image.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_padding',
            field=models.PositiveIntegerField(default=16, help_text='Extra pixels around face before saving (visual pad).'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_quality',
            field=models.PositiveIntegerField(default=95, help_text='If JPG, 1..100'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_save_threshold',
            field=models.FloatField(default=0.65, help_text='Archive when live match score ≥ this value (independent of recognition min-score).'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='crops_subdir',
            field=models.CharField(default='captures', help_text="Subfolder under each student’s gallery (e.g., 'captures').", max_length=32),
        ),
    ]
