# Generated by Django 5.2.5 on 2025-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_recognitionsettings_crops_apply_all_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='crops_opt_in',
            field=models.BooleanField(default=False, help_text='If true and global capture is enabled, archive top crops for this student.'),
        ),
    ]
