# Generated by Django 5.2.5 on 2025-09-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_faceembedding_crops_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='confirmed',
            field=models.BooleanField(db_index=True, default=False, help_text='Manually marked by a lunch supervisor as verified.'),
        ),
        migrations.AddField(
            model_name='recognitionsettings',
            name='pass_gap_window_sec',
            field=models.PositiveIntegerField(default=120, help_text='Gap in seconds to count a *new pass* for pass_count. Used to increment AttendanceRecord.pass_count when the same student reappears after this gap within the same period. Typical 60–240.We meant to use it for the LUNCH periods for the student waiting in queue, e.x. lunch-pri & lunch-sec'),
        ),
    ]
