# Generated by Django 5.2.5 on 2025-09-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_attendancerecord_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(choices=[('lunch', 'Lunch'), ('bus', 'Bus'), ('assembly', 'Assembly')], max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Dashboard tag',
                'verbose_name_plural': 'Dashboard tags',
            },
        ),
        migrations.AddField(
            model_name='periodtemplate',
            name='usage_tags',
            field=models.ManyToManyField(blank=True, help_text='Dashboards that should include this period', related_name='period_templates', to='attendance.dashboardtag'),
        ),
    ]
