# Generated by Django 5.2.5 on 2025-11-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_dashboardtag_periodtemplate_usage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('annual', 'Annual'), ('monthly', 'Monthly'), ('other', 'Other')], default='monthly', help_text='Annual / monthly / other – mainly for reporting.', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_subscriptions', to='attendance.student')),
            ],
            options={
                'ordering': ['student', 'start_date'],
                'indexes': [models.Index(fields=['student', 'status', 'start_date', 'end_date'], name='attendance__student_027430_idx')],
            },
        ),
    ]
