# Generated by Django 5.2.5 on 2025-11-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_student_grade'),
        ('attendance', '0022_lunchsubscription'),
    ]

    operations = [
    ]
