# Generated by Django 5.2.5 on 2025-11-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_merge_0022_alter_student_grade_0022_lunchsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
