# Generated by Django 5.2.5 on 2026-01-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_student_gender_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='lunch_eligible_at_time',
            field=models.BooleanField(blank=True, db_index=True, help_text="Snapshot: whether the student was eligible for lunch on this record's best_seen date. Saved at record creation time for audit/reporting.", null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lunch_reason_code',
            field=models.CharField(blank=True, choices=[('', '—'), ('paid_not_entered', 'Paid but not entered yet'), ('manager_approved', 'Manager approved / exception'), ('guest', 'Guest / visitor'), ('other', 'Other')], db_index=True, default='', help_text='Reason code when lunch confirmation needs explanation (esp. overrides).', max_length=32),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lunch_reason_notes',
            field=models.CharField(blank=True, default='', help_text='Optional notes to clarify the reason.', max_length=200),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lunch_subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription that made this record eligible (snapshot).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='attendance.lunchsubscription'),
        ),
    ]
