# Generated by Django 5.2.5 on 2026-03-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_attendancerecord_lunch_eligible_at_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchsubscription',
            name='end_date',
            field=models.DateField(db_index=True, help_text='Tip: If you are adjusting TWO subscriptions to remove an overlap, save after editing the first one, then edit the second and save.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='has_lunch',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
