# Generated by Django 5.2.5 on 2026-04-06 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_alter_lunchsubscription_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lunch_eligible_at_time',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lunch_reason_code',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lunch_reason_notes',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='lunch_subscription',
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percent', 'Percentage')], max_length=20)),
                ('value_iqd', models.IntegerField(default=0)),
                ('value_percent', models.PositiveSmallIntegerField(default=0)),
                ('min_same_day_confirmed_meals', models.PositiveSmallIntegerField(blank=True, help_text='Optional condition for same-day logic.', null=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('discount_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='attendance.discountprofile')),
                ('period_template', models.ForeignKey(blank=True, help_text='Blank means all periods.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_rules', to='attendance.periodtemplate')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LunchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('date_range', 'Date-range'), ('wallet', 'Wallet')], default='date_range', max_length=20)),
                ('insufficient_funds_mode', models.CharField(choices=[('deny', 'Deny'), ('allow_unpaid', 'Allow unpaid'), ('allow_negative', 'Allow negative')], default='deny', max_length=20)),
                ('allow_supervisor_confirm', models.BooleanField(default=True)),
                ('allow_supervisor_unconfirm', models.BooleanField(default=False)),
                ('allow_supervisor_refund', models.BooleanField(default=False)),
                ('require_reason_on_override', models.BooleanField(default=True)),
                ('require_reason_on_unconfirm', models.BooleanField(default=False)),
                ('require_reason_on_refund', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lunch_profiles', to='attendance.discountprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lunchsubscription',
            name='lunch_profile',
            field=models.ForeignKey(blank=True, help_text='Optional pricing/policy profile. Blank = basic date-range behavior.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='attendance.lunchprofile'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_iqd', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='attendance.student')),
            ],
            options={
                'ordering': ['student__h_code'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('topup', 'Top-up'), ('debit', 'Debit'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('unpaid', 'Unpaid')], db_index=True, max_length=20)),
                ('amount_iqd', models.IntegerField(help_text='Signed amount. Example: +10000 topup, -5000 debit, +5000 refund.')),
                ('balance_before_iqd', models.IntegerField(default=0)),
                ('balance_after_iqd', models.IntegerField(default=0)),
                ('reason_code', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='attendance.attendancerecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('reversed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_children', to='attendance.wallettransaction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='attendance.student')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='attendance.wallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LunchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_at_time', models.BooleanField(blank=True, db_index=True, null=True)),
                ('mode_snapshot', models.CharField(blank=True, choices=[('', '—'), ('date_range', 'Date-range'), ('wallet', 'Wallet'), ('exception', 'Exception')], db_index=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('denied', 'Denied'), ('unpaid', 'Unpaid'), ('refunded', 'Refunded'), ('voided', 'Voided')], db_index=True, default='pending', max_length=20)),
                ('price_base_iqd', models.IntegerField(default=0)),
                ('discount_iqd', models.IntegerField(default=0)),
                ('final_charge_iqd', models.IntegerField(default=0)),
                ('wallet_balance_before_iqd', models.IntegerField(default=0)),
                ('wallet_balance_after_iqd', models.IntegerField(default=0)),
                ('reason_code', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('reason_notes', models.CharField(blank=True, default='', max_length=200)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_record', to='attendance.attendancerecord')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_lunch_records', to=settings.AUTH_USER_MODEL)),
                ('lunch_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lunch_records', to='attendance.lunchprofile')),
                ('lunch_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lunch_records', to='attendance.lunchsubscription')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_lunch_records', to=settings.AUTH_USER_MODEL)),
                ('wallet_refund_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lunch_refund_records', to='attendance.wallettransaction')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lunch_charge_records', to='attendance.wallettransaction')),
            ],
            options={
                'ordering': ['-attendance_record__best_seen', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LunchProfilePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_iqd', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('lunch_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_prices', to='attendance.lunchprofile')),
                ('period_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lunch_profile_prices', to='attendance.periodtemplate')),
            ],
            options={
                'ordering': ['lunch_profile__name', 'period_template__order'],
                'unique_together': {('lunch_profile', 'period_template')},
            },
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='attendance__wallet__1eaeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['student', 'created_at'], name='attendance__student_3fd045_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['attendance_record', 'created_at'], name='attendance__attenda_7de8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['tx_type', 'created_at'], name='attendance__tx_type_2f68c1_idx'),
        ),
        migrations.AddIndex(
            model_name='lunchrecord',
            index=models.Index(fields=['status', 'mode_snapshot'], name='attendance__status_dbbdce_idx'),
        ),
        migrations.AddIndex(
            model_name='lunchrecord',
            index=models.Index(fields=['eligible_at_time'], name='attendance__eligibl_d68e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='lunchrecord',
            index=models.Index(fields=['confirmed_at'], name='attendance__confirm_2cb141_idx'),
        ),
        migrations.AddIndex(
            model_name='lunchrecord',
            index=models.Index(fields=['lunch_profile'], name='attendance__lunch_p_adb372_idx'),
        ),
        migrations.AddIndex(
            model_name='lunchrecord',
            index=models.Index(fields=['lunch_subscription'], name='attendance__lunch_s_404ff3_idx'),
        ),
    ]
