# Generated by Django 5.2.5 on 2026-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_discountprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsubscription',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('dashboard_postpaid', 'Dashboard postpaid')], db_index=True, default='manual', max_length=40),
        ),
    ]
