# Generated by Django 5.2.5 on 2026-04-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_mealsubscription_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealsubscription',
            options={'ordering': ['student', 'priority', 'start_date', 'id']},
        ),
        migrations.AddField(
            model_name='mealprofile',
            name='credit_limit_iqd',
            field=models.PositiveIntegerField(blank=True, help_text='Only used when mode=Wallet and insufficient funds mode=Allow negative. Blank = no negative limit. Example: 1000 means balance may go down to -1000 IQD only.', null=True),
        ),
        migrations.AddField(
            model_name='mealsubscription',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Lower number wins. Recommended: 1=primary, 2=fallback.'),
        ),
    ]
