# Generated by Django 5.2.5 on 2026-07-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_alter_mealsubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsubscription',
            name='plan_type',
            field=models.CharField(choices=[('annual', 'Annual'), ('monthly', 'Monthly'), ('other', 'Other')], default='monthly', help_text='Date-range: (Annual / monthly), or Wallet / other – mainly for reporting.', max_length=20),
        ),
    ]
