# Generated by Django 5.2.5 on 2026-07-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0031_alter_mealsubscription_plan_type"),
        ("cameras", "0009_camera_period_templates"),
        ("identity", "0002_seed_roletypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="faceembedding",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="Identity Person this embedding belongs to. Backfilled from student via StudentProfile.legacy_student. Nullable during the dual-FK transition window.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="identity.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="faceembedding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("person",),
                name="uniq_active_embedding_per_person",
            ),
        ),
    ]
