# Generated by Django 5.2.5 on 2026-07-07 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0035_attendanceevent_person_backfill"),
        ("identity", "0002_seed_roletypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="Identity Person this record belongs to. Backfilled from student via StudentProfile.legacy_student. Nullable during the dual-FK transition window.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="identity.person",
            ),
        ),
    ]
