# Generated by Django 5.2.5 on 2026-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0037_attendancerecord_person_backfill"),
        ("cameras", "0009_camera_period_templates"),
        ("identity", "0002_seed_roletypes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("person", "period"), ("student", "period")},
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["person", "period"], name="attendance__person__dad0f4_idx"
            ),
        ),
    ]
